####
# autotranslation for the "hindi" language
####
#
# THIS FILE WAS AUTOMATICALLY GENERATED
#
# this file was autogenerated from google translate
# there are bound to be problems, mistranslations, and cultural problems
#
# it is our sincerest hope that these will be corrected by the community
# over time
#
# we kindly ask for your patience, and any contributions you may wish to make
#
# the dev team is not fluent in these languages, and no actual offense is intended
#
# obviously, many of these can be shortened.  to do so properly would take
# a fluent language speaker who is also familiar with the BASIC programming
# language
#
# this file should be utf8
# entries on the left are the actual BASIC keywords
# entries on the right are the native versions of those keywords
# blank lines are allowed

[keywords]

# from ECMA-55 §5.2

END <= अत          # the end statement

# from ECMA-55 §9

ABS <= नरपकषमलय          # the absolute value function
ATN <= उलटसपरशरख          # the trigonomic arctangent function
COS <= कजय          # the trigonomic cosine function
EXP <= घतय          # the exponential / power function
INT <= परणक          # the integer / floor function
LOG <= लगरतम          # the natural log function
RND <= लढकन          # generate random number
SGN <= सकत          # determine the sign
SIN <= जय          # the trigonomic sine function
SQR <= वरगमल          # the square root function
TAN <= सपरशरख          # the trigonomic tangent function
DBL <= दहर          # convert to double

# from ECMA-55 §10

DEF <= परभषतकरन          # for user defined functions

# from ECMA-55 §11

LET <= हनदन          # for variable assignment

# from ECMA-55 §12
# NB: ECMA-55 has no ELSE statement

GO <= जन            # part of the GOTO and GOSUB
GOSUB <= पकरन      # formed from GO and SUB if no direct translation exists
GOTO <= कदन        # formed from GO and TO if no direct translation exists
TO <= क            # part of for/to/step/next constructs
IF <= अगर            # part of if/then constructs
THEN <= तब        # part of if/then constructs
SUB <= वषय          # beware, used as part of "go sub"
ON <= बदलन            # a sort of a switch statement
RETURN <= वपसकरन    # used to exit a subroutine
STOP <= खतम        # command to stop execution

# from ECMA-55 §13
# NB: translation for TO is in §12

FOR <= स          # part of for/to/step/next constructs
STEP <= कदम        # part of for/to/step/next constructs
NEXT <= अगल        # part of for/to/step/next constructs

# from ECMA-55 §14

PRINT <= परट      # to print things out

# from ECMA-55 §15

INPUT <= इनपट      # the input statement

# from ECMA-55 §16

READ <= पढन        # part of read / restore
RESTORE <= कफरसपढ  # part of read / restore

# from ECMA-55 §17

DATA <= आकड        # to embed data in the program

# from ECMA-55 §18

DIM <= आयम          # dimension arrays
OPTION <= वकलप    # see ECMA-55 §18.1
BASE <= आधर        # see ECMA-55 §18.1

# from ECMA-55 §19

REM <= टपपण          # see ECMA-55 §18.1

# from ECMA-55 §20

RANDOMIZE <= अनयमत

#### end of ECMA-55 defined constants
#
# it is worth noting that the following constants,
# while they may appear in other versions of BASIC,
# do NOT appear in ECMA-55:
#
# LOOP <= LOOP  # designed to evoke an error for testing

[errors]

# error messages

err0|गलत: फइल {0s}, पकत {1i}, कलम {2i}

