####
# autotranslation for the "yiddish" language
####
#
# THIS FILE WAS AUTOMATICALLY GENERATED
#
# this file was autogenerated from google translate
# there are bound to be problems, mistranslations, and cultural problems
#
# it is our sincerest hope that these will be corrected by the community
# over time
#
# we kindly ask for your patience, and any contributions you may wish to make
#
# the dev team is not fluent in these languages, and no actual offense is intended
#
# obviously, many of these can be shortened.  to do so properly would take
# a fluent language speaker who is also familiar with the BASIC programming
# language
#
# this file should be utf8
# entries on the left are the actual BASIC keywords
# entries on the right are the native versions of those keywords
# blank lines are allowed

[keywords]

# from ECMA-55 §5.2

END <= ויסלאזן          # the end statement

# from ECMA-55 §9

ABS <= אבסאלוטווערט          # the absolute value function
ATN <= פארקערטטאנדזשאנט          # the trigonomic arctangent function
COS <= קאסינע          # the trigonomic cosine function
EXP <= עקספאונענשאל          # the exponential / power function
INT <= ינטאדזשער          # the integer / floor function
LOG <= LOGARITHM          # the natural log function
RND <= זעמל          # generate random number
SGN <= צייכן          # determine the sign
SIN <= סינוס          # the trigonomic sine function
SQR <= קוואדראטווארצל          # the square root function
TAN <= טאנדזשאנט          # the trigonomic tangent function
DBL <= טאפל          # convert to double

# from ECMA-55 §10

DEF <= דעפינירן          # for user defined functions

# from ECMA-55 §11

LET <= לאזן          # for variable assignment

# from ECMA-55 §12
# NB: ECMA-55 has no ELSE statement

GO <= פונקציאנירן            # part of the GOTO and GOSUB
GOSUB <= רופן      # formed from GO and SUB if no direct translation exists
GOTO <= שפרונג        # formed from GO and TO if no direct translation exists
TO <= צו            # part of for/to/step/next constructs
IF <= ויב            # part of if/then constructs
THEN <= ווי        # part of if/then constructs
SUB <= סוב          # beware, used as part of "go sub"
ON <= יבערבייט            # a sort of a switch statement
RETURN <= ומקערן    # used to exit a subroutine
STOP <= געענדיקט        # command to stop execution

# from ECMA-55 §13
# NB: translation for TO is in §12

FOR <= פון          # part of for/to/step/next constructs
STEP <= טרעפל        # part of for/to/step/next constructs
NEXT <= ווייטער        # part of for/to/step/next constructs

# from ECMA-55 §14

PRINT <= פארקויפט      # to print things out

# from ECMA-55 §15

INPUT <= אריינשרייב      # the input statement

# from ECMA-55 §16

READ <= לייענען        # part of read / restore
RESTORE <= READEAD  # part of read / restore

# from ECMA-55 §17

DATA <= דאטע        # to embed data in the program

# from ECMA-55 §18

DIM <= ויסמעסטונג          # dimension arrays
OPTION <= בריירע    # see ECMA-55 §18.1
BASE <= באזע        # see ECMA-55 §18.1

# from ECMA-55 §19

REM <= באמערקונג          # see ECMA-55 §18.1

# from ECMA-55 §20

RANDOMIZE <= ראנדאמייז

#### end of ECMA-55 defined constants
#
# it is worth noting that the following constants,
# while they may appear in other versions of BASIC,
# do NOT appear in ECMA-55:
#
# LOOP <= LOOP  # designed to evoke an error for testing

[errors]

# error messages

err0|גרייז: טעקע {0s}, ליניע {1i}, זייל {2i}

